### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by yonpols** [ios-route-to-do/app#1]
/cc @codepathreview @codepath

**Comment by nickai** [comment]
Thanks for submitting your user stories and wireframes! Having such a good set of user stories and wireframes makes things a lot easier as your implement the project.

This seems very ambitious. Make sure to work in priority order for the "must have" features and then circle back and add the polish later.

The next step is to finish the MVP features by **end of day Wednesday (11/25) PST** and create another issue once you have completed that part.
