### ISSUE TITLE
Basic App

### ISSUE THREAD

**Issue by yonpols** [ios-route-to-do/app#8]
/cc @codepathreview @codepath

All basic functionality is there without connection with the backend. We focused on UX

**Comment by nickai** [comment]
Nice work! Getting the MVP done early goes a long way to setting you up for success on demo day.

This current week is now about **iterating on the core functionality** implemented by the app last week. This is the second sprint so spend your time this week filling in missing content, functionality, fixing bugs, improving the core flows, adding optionals, making sure to connect to the backend, etc.

The final week can then be dedicated to polishing your app to make it shine on demo day.

Let me know if I can be of assistance in any way. I'm really looking forward to seeing your **finished app on demo day (Dec 10th)**!
